# DEPLOYMENTS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skeleton-site
  name: skeleton-site
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skeleton-site
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skeleton-site
    spec:
      automountServiceAccountToken: false
      containers:
      - image: skeleton-site:v1
        imagePullPolicy: IfNotPresent
        name: skeleton-site
        resources:
          limits:
            cpu: 300m
            memory: "200Mi"
          requests:
            cpu: 200m
            memory: "100Mi"
